### ISSUE TITLE
Reflashing firmware: No serial data received error

### ISSUE THREAD

**Issue by wraetz-dev** [QuickSpot/walter-micropython#2]
When attempting interact with Walter using esptool.py, I am consistently getting a "No serial data received" error. 

This seems to occur after the first reflash of micropython using the command:

`esptool.py -p COM9 --chip esp32s3 write_flash -z 0 flash_name.bin`

After that, I only get the following output from esptool.py:

`esptool.py v4.8.dev5`
`Serial port COM9`
`Connecting......................................`
`A fatal error occurred: Failed to connect to Espressif device: No serial data received.`

I am consistently able to get to the command line using Putty on windows, so it does not appear to be a TX/RX issue. I have tried this sequence on two boards so far with the same behavior. Both times I have flashed the stock esp32s3 firmware in this repo.

Are there any troubleshooting steps I can take to try and diagnose the issue?

**Comment by daanpape** [comment]
Hi @wraetz-dev,

Can you let me know which micropython image that you flashed after which Walter stopped responding to esptool.py?

Best regards,
Daan

**Comment by wraetz-dev** [comment]
Daan,

I flashed the [micropython binary](https://github.com/QuickSpot/walter-micropython/blob/main/micropython/ESP32_GENERIC_S3-20231005-v1.21.0.bin) from this repo. 

Thanks,
Will

**Comment by vThibo** [comment]
Hi @wraetz-dev 

After flashing the MicroPython binary, esptool doesn't seem to be able to automatically put the ESP32-S3 in bootloader mode through the USB serial anymore. In order to manually put it in bootloader mode, connect Walter's pin GPIO0/3V3_E to GND while cycling power. After this, the COM port number will likely have changed, and esptool can flash to the board again.

**Comment by wraetz-dev** [comment]
This works very well! Thank you for your help @vThibo

**Comment by MRIIOT** [comment]
> Hi @wraetz-dev
> 
> After flashing the MicroPython binary, esptool doesn't seem to be able to automatically put the ESP32-S3 in bootloader mode through the USB serial anymore. In order to manually put it in bootloader mode, connect Walter's pin GPIO0/3V3_E to GND while cycling power. After this, the COM port number will likely have changed, and esptool can flash to the board again.

This explains my behavior as well.
